Public Class student
    Public Property FullName() As String = ""
    Public Property Indexn() As String = ""
    Public Property English() As String = ""
    Public Property Engg() As String = ""
    Public Property Math() As String = ""
    Public Property Mathg() As String = ""
    Public Property Cre() As String = ""
    Public Property Creg() As String = ""
    Public Property Social() As String = ""
    Public Property Socialg() As String = ""
    Public Property Geo() As String = ""
    Public Property Geog() As String = ""
    Public Property Physic() As String = ""
    Public Property Physicg() As String = ""
    Public Property Biology() As String = ""
    Public Property Biologyg() As String = ""
    Public Property Ecomm() As String = ""
    Public Property Ecommg() As String = ""
    Public Property Engineer() As String = ""
    Public Property Engineerg() As String = ""
    Public Property Art() As String = ""
    Public Property Artg() As String = ""
    Public Property Score() As String = ""
    Public Property Average() As String = ""

    Public Property Finalg() As String = ""

End Class
